keys:
  # The "Master Keys" (You)
  - &apollo_user  age1kztzsdg40uyws3mm69nww87qmdqws2zpua6ym6hrcfcgpkp0vecspkf2ya

  # The "Host Keys" (The Machines)
  - &mars_host    age15jjutm32rsyy35x4lf6p9t5nmsx5gmzqmhykz95dt22jrvphrpssdll0xe
  - &mercury_host age1_mercury_output_here...
  - &venus_host   age17au70tcp7jyyl9ln2wgdmef9tpt6ex6jy7qayezp44rsdhzrlqtqmg4ftz
creation_rules:
  # Secrets that EVERY machine needs (e.g., your user password)
  - path_regex: secrets/common\.yaml$
    key_groups:
      - age:
          - *apollo_user
          - *mars_host
          - *mercury_host
          - *venus_host

  # Secrets unique to Mars (e.g., specific GPU settings or local backups)
  # - path_regex: secrets/mars\.yaml$
  #  key_groups:
  #    - age:
  #        - *apollo_user
  #        - *mars_host
