{
  config,
  lib,
  pkgs,
  ...
}:

let
  cfg = config.myFeatures.platforms.desktops.mangowc;
  stylixEnabled = config.myFeatures.platforms.styling.stylix.enable or false;
in
{
  options.myFeatures.platforms.desktops.mangowc = {
    enable = lib.mkEnableOption "MangoWC / MangoWM (SceneFX-accelerated Wayland Compositor)";

    modKey = lib.mkOption {
      type = lib.types.enum [
        "SUPER"
        "ALT"
      ];
      default = "SUPER";
      description = "Primary modifier key for MangoWC bindings";
    };

    borderWidth = lib.mkOption {
      type = lib.types.int;
      default = 2;
      description = "Window border width in pixels";
    };

    gaps = lib.mkOption {
      type = lib.types.int;
      default = 8;
      description = "Window gaps in pixels";
    };

    extraConfig = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [ ];
      description = "Extra configuration lines appended to ~/.config/mango/config.conf";
    };
  };

  config = lib.mkIf cfg.enable {
    environment.systemPackages = with pkgs; [
      mangowc
      wl-clipboard
      libnotify
      brightnessctl
      fuzzel
      swaybg
      swayidle
      swaylock
      grim
      slurp
    ];

    xdg.portal = {
      enable = true;
      extraPortals = [ pkgs.xdg-desktop-portal-wlr ];
      config.mangowc.default = [
        "wlr"
        "gtk"
      ];
    };

    home-manager.users = lib.genAttrs config.myFeatures.core.system.users.usernames (_name: {
      xdg.configFile."mango/config.conf".text = ''
        # MangoWC / MangoWM Configuration generated by Solar
        mod = ${cfg.modKey}
        border_width = ${toString cfg.borderWidth}
        gaps = ${toString cfg.gaps}
        focus_color = ${if stylixEnabled then "#${config.lib.stylix.colors.base0D}" else "#78a9ff"}
        unfocus_color = ${if stylixEnabled then "#${config.lib.stylix.colors.base02}" else "#504945"}

        # Keybindings
        bind = $mod, Q, spawn, ghostty
        bind = $mod SHIFT, Q, spawn, firefox
        bind = $mod, SPACE, spawn, fuzzel
        bind = $mod, D, spawn, fuzzel
        bind = $mod, C, killclient
        bind = $mod SHIFT, E, quit
        bind = $mod, V, togglefloating
        bind = $mod, F, togglefullscreen

        # Focus
        bind = $mod, Left, focusstack, -1
        bind = $mod, Right, focusstack, 1
        bind = $mod, H, focusstack, -1
        bind = $mod, L, focusstack, 1
        bind = $mod, J, focusstack, 1
        bind = $mod, K, focusstack, -1

        # Tags / Workspaces
        bind = $mod, 1, view, 1
        bind = $mod, 2, view, 2
        bind = $mod, 3, view, 3
        bind = $mod, 4, view, 4
        bind = $mod, 5, view, 5
        bind = $mod, 6, view, 6
        bind = $mod, 7, view, 7
        bind = $mod, 8, view, 8
        bind = $mod, 9, view, 9

        # Move to Tags
        bind = $mod SHIFT, 1, tag, 1
        bind = $mod SHIFT, 2, tag, 2
        bind = $mod SHIFT, 3, tag, 3
        bind = $mod SHIFT, 4, tag, 4
        bind = $mod SHIFT, 5, tag, 5
        bind = $mod SHIFT, 6, tag, 6
        bind = $mod SHIFT, 7, tag, 7
        bind = $mod SHIFT, 8, tag, 8
        bind = $mod SHIFT, 9, tag, 9

        ${lib.concatStringsSep "\n" cfg.extraConfig}
      '';
    });

    preservation.preserveAt."${config.myFeatures.core.system.preservation.persistentPath}" =
      lib.mkIf (config.myFeatures.core.system.preservation.enable or false)
        {
          users = lib.genAttrs config.myFeatures.core.system.users.usernames (_name: {
            directories = [
              ".config/mango"
            ];
          });
        };
  };
}
