# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "ahci" "xhci_pci" "usb_storage" "usbhid" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/fce8da37-711c-4ca6-b53a-40efb6bbdfab";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/825E-7E48";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };
  
  # Windows Boot Partition
  fileSystems."/boot/EFI/windows" = 
    {
      device = "/dev/disk/by-uuid/6823-22BA";
      fsType = "vfat";
      options = [ "nofail" "noauto" ];
    };

  fileSystems."/home/nvme" =
    { device = "/dev/disk/by-uuid/bd61e42b-16e9-4222-9075-d6318db371ca";
      fsType = "ext4";
    };

  fileSystems."/home/ssd" =
    { device = "/dev/disk/by-uuid/4ecb3d2d-85b7-4f08-82a5-e32ff1801100";
      fsType = "ext4";
    };

  fileSystems."/home/hdd" =
    { device = "/dev/disk/by-uuid/5ee3390e-5e47-4794-953b-a6cde2a5f955";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/1a7a0a79-784e-44fb-b4ba-72ed39ecc68a"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp12s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp13s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
