# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  # Earbuds
  boot.extraModprobeConfig = ''
  options snd-hda-intel patch=hda-jack-retask.fw
  '';

  hardware.firmware = [
    (pkgs.runCommand "hda-jack-retask-fw" {} ''
      mkdir -p $out/lib/firmware
      cat <<EOF > $out/lib/firmware/hda-jack-retask.fw
  [codec]
  0x10ec0897 0x1022c950 0

  [pincfg]
  0x19 0x03a11020
  0x1b 0x40000000
  EOF
    '')
  ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];
  boot.kernelParams = [ "snd_hda_intel.model=alc897-headset-multi" "snd_hda_intel.jack_detect=0" ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/14fad7d0-a853-4077-b00b-45a319a12f8c";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/E88B-D3A7";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/751f8bd1-ce8d-473e-9f22-91dd2f6e00c8"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp1s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp4s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
