apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-data
  namespace: games
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 20Gi
