apiVersion: v1
kind: Service
metadata:
  name: minecraft
  namespace: games
spec:
  type: ClusterIP
  ports:
    - port: 25565
      targetPort: 25565
      name: minecraft
  selector:
    app: minecraft
