# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  boot.initrd.systemd = {
    enable = true;
    tpm2.enable = true;
  };
  
  fileSystems."/" =
    { device = "/dev/mapper/luks-9e40bb0e-dbe2-4d30-b016-29c386b9c476";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-9e40bb0e-dbe2-4d30-b016-29c386b9c476" = {
    device = "/dev/disk/by-uuid/9e40bb0e-dbe2-4d30-b016-29c386b9c476";
    crypttabExtraOpts = [ "tpm2-device=auto" ];
    preLVM = true;
    allowDiscards = true;
  };

  # Swap Partition (p3) - This fixes the 90s hang
  boot.initrd.luks.devices."luks-95dd7114-f8ee-4b6f-a8b1-2285dafdf137" = {
    device = "/dev/disk/by-uuid/95dd7114-f8ee-4b6f-a8b1-2285dafdf137";
    crypttabExtraOpts = [ "tpm2-device=auto" ];
    preLVM = true;
    allowDiscards = true;
  };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/4476-6407";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-95dd7114-f8ee-4b6f-a8b1-2285dafdf137"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
