apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-credentials
  namespace: cloudflared
type: Opaque
stringData:
  credentials.json: |
    {
      "AccountTag": "replace-with-your-account-tag",
      "TunnelSecret": "replace-with-your-tunnel-secret",
      "TunnelID": "replace-with-your-tunnel-id"
    }
  TUNNEL_TOKEN: "replace-with-your-cloudflared-tunnel-token"
